### ISSUE TITLE
 Not able to connect to http://localhost:5601/

### ISSUE THREAD

**Issue by pofican** [timroes/kibana4-vagrant#1] opened 2015-02-17 06:42 UTC
On windows not able to connect http://localhost:5601/, Below is the output when I run vagrant up command:

> > > > > vagrant up
> > > > > Bringing machine 'default' up with 'virtualbox' provider...
> > > > > ==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and in
> > > > > stall...
> > > > >     default: Box Provider: virtualbox
> > > > >     default: Box Version: >= 0
> > > > > ==> default: Loading metadata for box 'ubuntu/trusty64'
> > > > >     default: URL: https://atlas.hashicorp.com/ubuntu/trusty64
> > > > > ==> default: Adding box 'ubuntu/trusty64' (v14.04) for provider: virtualbox
> > > > >     default: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/vers
> > > > > ions/14.04/providers/virtualbox.box
> > > > >     default: Progress: 100% (Rate: 863k/s, Estimated time remaining: --:--:--)
> > > > > ==> default: Successfully added box 'ubuntu/trusty64' (v14.04) for 'virtualbox'!

==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: kibana4-vagrant-master_default_14241547
50010_39882
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 5601 => 5601 (adapter 1)
    default: 9200 => 9200 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

Second time when I run same command I am getting this:

C:\Users\ydemir\Desktop\kibana4-vagrant-master\kibana4-vagrant-master>vagrant up

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: VirtualBox VM is already running.

**Comment by timroes** [comment] 2015-02-17 14:54
This is a problem with vagrant (and not this vm in special), but I try my best to help you.

I would first try to look at the following stackoverflow answers, which looks kind of promising:

http://stackoverflow.com/questions/22575261/vagrant-stuck-connection-timeout-retrying

You would have to add the suggested code snippets to the `Vagrantfile` in line 19 (before the closing `end`).

Only other suggestion I have is that a firewall might be blocking this?!

If any of this solved your problem please tell me and I will check if I can make a check ,so that this option is enabled for windows by default in this vm.

**Comment by pofican** [comment] 2015-02-17 18:55
So thanks for your help, I added that code snippet in the  Vagrantfile  and disabled firewall. After disabling firewall a vm box started to boot but went in to an invalid state right away and virtual box gave me this error "VT-x/AMD-V hardware acceleration is not available on your system. Your 64-bit guest will fail to detect a 64-bit CPU  and will not be able to boot." Though I have a 64 bit CPU. I think in this case my CPU does not support VT-x. The turnarounds for this needs some elbow grease and I will give your project a try on my Linux machine instead :)

**Comment by timroes** [comment] 2015-02-17 20:44
If you don't have a really old CPU (around 7 years and older, Pentium 4 or newer as far as I remember) your CPU should support that feature. But unfortunately it is turned of in BIOS for a lot of mainboards by default. In that case you would need to search for a setting to enable VT-x/AMD-V (or often just called Virtualization) in your BIOS and it should work afterwards. Of course I always welcome using things on Linux :-) if you want to run it on windows, I would give the search for that BIOS setting a short try.

**Comment by pofican** [comment] 2015-02-17 21:01
Well yes you are right actually, I am getting the same error on Ubuntu... I would like to set it up on ubuntu if I can so nevermind the windows thing... WEre you able to run this on an Ubuntu machine? If so did you get the same error? If so what was your solution for it? And you are right this issue is not related to your code we can close it...

**Comment by timroes** [comment] 2015-02-17 21:09
I got this successfully running on different OS systems (and different Linux distributions). But I know the error and it is usually caused by the disabled VT-x setting in the BIOS. The settings might look something like the following:

![BIOS setting](http://docs.oracle.com/cd/E19790-01/820-4056-11/figures/cpu.gif)

In that case you would have to enable the _Intel (R) Virtualization Tech_. If you don't find that setting in your BIOS settings, feel free to tell me which mainboard you have and I try too look where you can find the setting for your mainboard. You can figure out what mainboard you have on linux with the commands `cat /sys/devices/virtual/dmi/id/board_name` and `cat /sys/devices/virtual/dmi/id/board_vendor`.

I will also close this bug, but feel free to anyway comment here for further help.

**Closed as completed by timroes** 2015-02-17 21:09 UTC

**Comment by pofican** [comment] 2015-02-17 21:14
OK thanks, for a quick solution I tried changing ubuntu/trusy64 to ubuntu/trusty32 and the vm is up and running now asking for a password, http://localhost:9200/ this host is up, http://localhost:5601/ I am getting connection was reset error and the kibana page is not able to load. 
I did type vagrant provision here is what I see:
pofican@Pofican:~/kibana4-vagrant-master$ vagrant provision
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20150217-6586-wrjhcf.sh
==> default: stdin: is not a tty
==> default: elasticsearch  1.4.3
==> default:  \* Starting Elasticsearch Server
==> default:    ...done.
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20150217-6586-eeso2s.sh
==> default: stdin: is not a tty
==> default: update-rc.d: warning: /etc/init.d/kibana missing LSB information
==> default: update-rc.d: see http://wiki.debian.org/LSBInitScripts
==> default:  Adding system startup for /etc/init.d/kibana ...
==> default:    /etc/rc0.d/K10kibana -> ../init.d/kibana
==> default:    /etc/rc1.d/K10kibana -> ../init.d/kibana
==> default:    /etc/rc6.d/K10kibana -> ../init.d/kibana
==> default:    /etc/rc2.d/S99kibana -> ../init.d/kibana
==> default:    /etc/rc3.d/S99kibana -> ../init.d/kibana
==> default:    /etc/rc4.d/S99kibana -> ../init.d/kibana
==> default:    /etc/rc5.d/S99kibana -> ../init.d/kibana
==> default: Starting Kibana. This might take some time, even after the script has been finished executing.
==> default: So please be patient ...

I am wondering if I am on the right track it has been 5 mins do I need to be more patient at this point? :)

**Comment by timroes** [comment] 2015-02-17 21:22
Yeah 32bit will work if you have that disabled, since that can be software emulated afaik (but won't be really fast). You should really give the BIOS settings a try, if your CPU supports 64 bit in general (as you said, and as nearly all modern CPU do). That way you would get much faster, and it should work without any further changes.

If you want to stick without that BIOS setting enabled, you can use the 32 bit VM as you edit it, but unfortunately you would also need the 32bit Kibana in that case:
- Download the [Kibana 32 bit package](https://download.elasticsearch.org/kibana/kibana/kibana-4.0.0-rc1-linux-x86.tar.gz)
- Place it in the `provisioning/files` folder
- Change the `provisioning/kibana.sh` script, so that it references the downloaded file in line 9.

I used the 64 bit version, since most often software nowadays is designed for 64 bit and all modern CPUs support 64 bit (with the small disadvantage, that you might need to enable it in BIOS).

**Comment by pofican** [comment] 2015-02-17 22:01
Thanks Tim, I am not able to bring up http://localhost:5601 and now I keep getting the below output, I think I am stuck in one of loops in your code where it checks for time-out. I don't know what I am missing here but I decided to use my own elastic search and kibana instead of a vagrant machine...

==> default:  \* Starting Elasticsearch Server
==> default:    ...done.
==> default: Waiting for elasticsearch to startup ...
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .
==> default: .

continues...

**Comment by timroes** [comment] 2015-02-17 22:13
A sorry I forgot, that you would also need a 32 bit java (elasticsearch should actually be fine).

You have to visit the [oracle download page](http://www.oracle.com/technetwork/java/javase/downloads/jre7-downloads-1880261.html) and download the JRE for Linux x86 and place it to `provisioning/files/` and update the filename in `provisioning/elasticsearch.sh` in line 7 to match the new filename.

If this works for you, and elasticsearch is then able to start (please don't forget to `vagrant destroy` between this not really working tries) I will think about putting this together into one vagrantfile, but I would need to make the Git 50 MB larger for the 32 bit binaries.. which I still consider.

**Comment by pofican** [comment] 2015-02-17 22:24
OK finally I got it working, I wanted a quick solution just to test Kibana beta version so here is the steps summarized for the people who also wants a quick fix (I copy pasted from above conversation): 
- Change ubuntu/trustu64 to ubuntu/trusty32
- Download the Kibana 32 bit package
  - Place it in the provisioning/files folder
  - Change the provisioning/kibana.sh script, so that it references the downloaded file in line 9.
- Visit the oracle download page and download the JRE for Linux x86 and place it to provisioning/files/ and update the filename in provisioning/elasticsearch.sh in line 7 to match the new filename.

I think this is all I changed I hope it works for the other people :)

**Comment by timroes** [comment] 2015-02-17 22:42
I made an alternative 32 bit version, in a new commit. You could download the new edition, and there is now a config file called `config.yaml` which you can use to specify, that you need a 32bit version (and also justify the memory the virtual machine should get). I also added these changes to the README.

If you could try out the new commit and tell me if this works for you (it seemed to work for me, but on the other hand, also the 64 bit machine worked for me :D) I would very much appreciate your feedback. And thanks for your contribution, so other 32 bit users might have it easier to try out Kibana 4 in the future.

**Comment by pofican** [comment] 2015-02-18 21:31
Hi Tim,

I gave it a try with the latest repository you have and it is working fine. Both repositories gave the below error and this how I fixed that issue in my code, just writing it here for future refenrece incase some other person faces a similar issue. 

ERROR MESSAGE:
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 9200 is already in use
on the host machine.

To fix this, modify your current projects Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 9200, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding.
SOLUTION:
replace the forwarded_port configs with the below guest and host configurations.
  config.vm.network "forwarded_port", guest: 5601, host: 5601
  config.vm.network "forwarded_port", guest: 81, host: 8081

In addition to this I got the below error when executed vagrant up but the locahost @ 5601 works fine...

**Comment by timroes** [comment] 2015-02-18 22:01
This is due to the reason, that you had already running something on port 9200 (most likely another elasticsearch instance) on your machine. Either you started this by having another vagrant machine already running with that instance, or because you had a local elasticsearch running otherwise. Solution in this case is not to modify the Vagrantfile, but to stop the other elasticsearch instance :-)

**Comment by pofican** [comment] 2015-02-18 22:04
I checked that and the only instance that is running my desktop is the one in that vagrant file meaning only one elastic search is running at the moment but I still get this error... That is why I finally changed the ports and it worked finally.

**Comment by RickyHorne** [comment] 2015-03-20 00:53
I couldn't connect to :5601 kibana also.  I couldn't do a 'service kibana4 start' - I would get 'env: /etc/init.d/kibana4: No such file or directory'
I found that the /etc/init.d/kibana4 file is in [dos] format.  I did a sudo vi kibana4 and then ;set fileformat=unix and saved it.  I was then able to start the daemon.
ref: http://serverfault.com/questions/592702/no-such-file-or-directory-error-when-trying-to-execute-startup-script-in-debian

**Comment by timroes** [comment] 2015-03-21 10:24
Since I was not able to reproduce this, I assume it happens when your host is a windows machine. I anyway modified the provisioning script, so this error should not occur anymore. Perhaps some of you can acknowledge me if the fix worked, I added in 672823df1df374a612d153de3a02e800230fc2e3?

**Comment by RickyHorne** [comment] 2015-03-21 13:38
Yup, it was Windows, that fixed it. 
Thanks, Rick
